### ISSUE TITLE
从txt到e的时候 很多代码被注释了

### ISSUE THREAD

**Issue by 1592363624** [SalHe/ebuild#2]
本应该是正常的代码
![image](https://user-images.githubusercontent.com/50036597/236854930-15f241c3-45dd-4855-a54a-6f55edcdc029.png)

**Comment by SalHe** [comment]
这个问题应该是属于e2txt的。如果方便的话麻烦提供一个复现问题的源码文件，我确认一下问题所在。

**Comment by 1592363624** [comment]
测试文件：http://alist.52shell.ltd:5244/d/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/%E6%B8%B8%E5%AE%A2%E7%A9%BA%E9%97%B4/%E6%B5%8B%E8%AF%95.e?sign=CoNXA6geo9AzXkTAnQa5c1WfR9KWJ5caszMZB39YLLA=:0




方便的话可以加个QQ：1592363624

**Comment by 1592363624** [comment]
> 这个问题应该是属于e2txt的。如果方便的话麻烦提供一个复现问题的源码文件，我确认一下问题所在。

我感觉随便一个都会这样子  也许是特定的什么格式的就被注释了

**Comment by 1592363624** [comment]
> 这个问题应该是属于e2txt的。如果方便的话麻烦提供一个复现问题的源码文件，我确认一下问题所在。

这是模块链接  刚才忘了：http://alist.52shell.ltd:5244/d/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/%E6%B8%B8%E5%AE%A2%E7%A9%BA%E9%97%B4/MyQQ%20Dev%2020211204.ec?sign=I-3ITxkSjP8B9JKusqYt75tkLTO1UVQAE9JGEZ_t4II=:0    

不用模块也应该可以测试出问题  只是不能编译

**Comment by SalHe** [comment]
e2txt 处理问题，暂时无能为力

**Comment by SalHe** [comment]
已向E2EE官方反馈，官方应该是暂无计划支持。本项目会尝试转向开源项目[TextECode](https://github.com/OpenEpl/TextECode)，如果能够正常支持，会在新版本中引入。

![0DT(7()@L`QNGGPO019MG}9](https://user-images.githubusercontent.com/8342541/236990725-72311179-7818-492d-acd1-bfd304d12042.png)
